var newQuertyKeys = [
        [{id:"192",displayChars:"` ~",keyValues:"`~"},{id:"49",displayChars:"1 !",keyValues:"1!"},{id:"50",displayChars:"2 @",keyValues:"2@"},{id:"51",displayChars:"3 #",keyValues:"3#"},{id:"52",displayChars:"4 $",keyValues:"4$"},{id:"53",displayChars:"5 %",keyValues:"5%"},{id:"54",displayChars:"6 ^",keyValues:"6^"},{id:"55",displayChars:"7 &",keyValues:"7&"},{id:"56",displayChars:"8 *",keyValues:"8*"},{id:"57",displayChars:"9 (",keyValues:"9("},{id:"48",displayChars:"0 )",keyValues:"0)"},{id:"189",displayChars:"- _",keyValues:"-_"},{id:"187",displayChars:"= +",keyValues:"=+"},{id:"8",displayChars:"Backspace",keyValues:""}],
        [{id:"9",displayChars:"Tab",keyValues:"Tab"},{id:"81",displayChars:"Q",keyValues:"qQ"},{id:"87",displayChars:"W",keyValues:"wW"},{id:"69",displayChars:"E",keyValues:"eE"},{id:"82",displayChars:"R",keyValues:"rR"},{id:"84",displayChars:"T",keyValues:"tT"},{id:"89",displayChars:"Y",keyValues:"yY"},{id:"85",displayChars:"U",keyValues:"uU"},{id:"73",displayChars:"I",keyValues:"iI"},{id:"79",displayChars:"O",keyValues:"oO"},{id:"80",displayChars:"P",keyValues:"pP"},{id:"219",displayChars:"[ {",keyValues:"[{"},{id:"221",displayChars:"] }",keyValues:"]}"},{id:"220",displayChars:"\\ |",keyValues:"\\|"}],
        [{id:"20",displayChars:"Caps",keyValues:"Caps"},{id:"65",displayChars:"A",keyValues:"aA"},{id:"83",displayChars:"S",keyValues:"sS"},{id:"68",displayChars:"D",keyValues:"dD"},{id:"70",displayChars:"F",keyValues:"fF"},{id:"71",displayChars:"G",keyValues:"gG"},{id:"72",displayChars:"H",keyValues:"hH"},{id:"74",displayChars:"J",keyValues:"jJ"},{id:"75",displayChars:"K",keyValues:"kK"},{id:"76",displayChars:"L",keyValues:"lL"},{id:"186",displayChars:"; :",keyValues:";:"},{id:"222",displayChars:"’ \"",keyValues:"’\""},{id:"13",displayChars:"Enter",keyValues:"Enter"}],
        [{id:"16",displayChars:"Shift",keyValues:"Shift"},{id:"90",displayChars:"Z",keyValues:"zZ"},{id:"88",displayChars:"X",keyValues:"xX"},{id:"67",displayChars:"C",keyValues:"cC"},{id:"86",displayChars:"V",keyValues:"vV"},{id:"66",displayChars:"B",keyValues:"bB"},{id:"78",displayChars:"N",keyValues:"nN"},{id:"77",displayChars:"M",keyValues:"mM"},{id:"188",displayChars:", <",keyValues:",<"},{id:"190",displayChars:". >",keyValues:".>"},{id:"191",displayChars:"/ ?",keyValues:"/?"},{id:"16",displayChars:"Shift",keyValues:"Shift"}],
        [{id:"17",displayChars:"Ctrl",keyValues:"Ctrl"},{id:"91",displayChars:"Win",keyValues:"Win"},{id:"18",displayChars:"Alt",keyValues:"Alt"},{id:"32",displayChars:"Space",keyValues:" "},{id:"18",displayChars:"Win",keyValues:"Win"},{id:"92",displayChars:"Alt",keyValues:"Alt"},{id:"93",displayChars:"Menu",keyValues:"Menu"},{id:"17",displayChars:"Ctrl",keyValues:"Ctrl"}]
    ];
var newKoreanKeys = [
        [{id:"192",displayChars:"` ~",keyValues:"`~"},{id:"49",displayChars:"1 !",keyValues:"1!"},{id:"50",displayChars:"2 @",keyValues:"2@"},{id:"51",displayChars:"3 #",keyValues:"3#"},{id:"52",displayChars:"4 $",keyValues:"4$"},{id:"53",displayChars:"5 %",keyValues:"5%"},{id:"54",displayChars:"6 ^",keyValues:"6^"},{id:"55",displayChars:"7 &",keyValues:"7&"},{id:"56",displayChars:"8 *",keyValues:"8*"},{id:"57",displayChars:"9 (",keyValues:"9("},{id:"48",displayChars:"0 )",keyValues:"0)"},{id:"189",displayChars:"- _",keyValues:"-_"},{id:"187",displayChars:"= +",keyValues:"=+"},{id:"8",displayChars:"Backspace",keyValues:""}],
        [{id:"9",displayChars:"Tab",keyValues:"Tab"},{id:"81",displayChars:"ㅂ",keyValues:"ㅂㅃ"},{id:"87",displayChars:"ㅈ",keyValues:"ㅈㅉ"},{id:"69",displayChars:"ㄷ",keyValues:"ㄷㄸ"},{id:"82",displayChars:"ㄱ",keyValues:"ㄱㄲ"},{id:"84",displayChars:"ㅅ",keyValues:"ㅅㅆ"},{id:"89",displayChars:"ㅛ",keyValues:"ㅛ"},{id:"85",displayChars:"ㅕ",keyValues:"ㅕ"},{id:"73",displayChars:"ㅑ",keyValues:"ㅑ"},{id:"79",displayChars:"ㅐ ㅒ",keyValues:"ㅐㅒ"},{id:"80",displayChars:"ㅔ ㅖ",keyValues:"ㅔㅖ"},{id:"219",displayChars:"[ {",keyValues:"[{"},{id:"221",displayChars:"] }",keyValues:"]}"},{id:"220",displayChars:"\\ |",keyValues:"\\|"}],
        [{id:"20",displayChars:"Caps",keyValues:"Caps"},{id:"65",displayChars:"ㅁ",keyValues:"ㅁ"},{id:"83",displayChars:"ㄴ",keyValues:"ㄴ"},{id:"68",displayChars:"ㅇ",keyValues:"ㅇ"},{id:"70",displayChars:"ㄹ",keyValues:"ㄹ"},{id:"71",displayChars:"ㅎ",keyValues:"ㅎ"},{id:"72",displayChars:"ㅗ",keyValues:"ㅗ"},{id:"74",displayChars:"ㅓ",keyValues:"ㅓ"},{id:"75",displayChars:"ㅏ",keyValues:"ㅏ"},{id:"76",displayChars:"ㅣ",keyValues:"ㅣ"},{id:"186",displayChars:"; :",keyValues:";:"},{id:"222",displayChars:"\' \"",keyValues:"\'\""},{id:"13",displayChars:"Enter",keyValues:"Enter"}],
        [{id:"16",displayChars:"Shift",keyValues:"Shift"},{id:"90",displayChars:"ㅋ",keyValues:"ㅋ"},{id:"88",displayChars:"ㅌ",keyValues:"ㅌ"},{id:"67",displayChars:"ㅊ",keyValues:"ㅊ"},{id:"86",displayChars:"ㅍ",keyValues:"ㅍ"},{id:"66",displayChars:"ㅠ",keyValues:"ㅠ"},{id:"78",displayChars:"ㅜ",keyValues:"ㅜ"},{id:"77",displayChars:"ㅡ",keyValues:"ㅡ"},{id:"188",displayChars:", <",keyValues:",<"},{id:"190",displayChars:". >",keyValues:".>"},{id:"191",displayChars:"/ ?",keyValues:"/?"},{id:"16",displayChars:"Shift",keyValues:"Shift"}],
        [{id:"17",displayChars:"Ctrl",keyValues:"Ctrl"},{id:"91",displayChars:"Win",keyValues:"Win"},{id:"18",displayChars:"Alt",keyValues:"Alt"},{id:"32",displayChars:"Space",keyValues:" "},{id:"18",displayChars:"Win",keyValues:"Win"},{id:"92",displayChars:"Alt",keyValues:"Alt"},{id:"93",displayChars:"Menu",keyValues:"Menu"},{id:"17",displayChars:"Ctrl",keyValues:"Ctrl"}]
    ];
var newTaiwaneseKeys = [
        [{id:"192",displayChars:"` ~",keyValues:"`~"},{id:"49",displayChars:"ㄅ",keyValues:"ㄅ"},{id:"50",displayChars:"ㄉ",keyValues:"ㄉ"},{id:"51",displayChars:"ˇ",keyValues:"ˇ"},{id:"52",displayChars:"ˋ",keyValues:"ˋ"},{id:"53",displayChars:"ㄓ",keyValues:"ㄓ"},{id:"54",displayChars:"ˊ",keyValues:"ˊ"},{id:"55",displayChars:"˙",keyValues:"˙"},{id:"56",displayChars:"ㄚ",keyValues:"ㄚ"},{id:"57",displayChars:"ㄞ",keyValues:"ㄞ"},{id:"48",displayChars:"ㄢ",keyValues:"ㄢ"},{id:"189",displayChars:"ㄦ",keyValues:"ㄦ"},{id:"187",displayChars:"= +",keyValues:"=+"},{id:"8",displayChars:"Backspace",keyValues:""}],
        [{id:"9",displayChars:"Tab",keyValues:"Tab"},{id:"81",displayChars:"ㄆ",keyValues:"ㄆ"},{id:"87",displayChars:"ㄊ",keyValues:"ㅈㅉ"},{id:"69",displayChars:"ㄍ",keyValues:"ㄍ"},{id:"82",displayChars:"ㄐ",keyValues:"ㄐ"},{id:"84",displayChars:"ㄔ",keyValues:"ㄔ"},{id:"89",displayChars:"ㄗ",keyValues:"ㄗ"},{id:"85",displayChars:"ㅡ",keyValues:"ㅡ"},{id:"73",displayChars:"ㄛ",keyValues:"ㄛ"},{id:"79",displayChars:"ㄟ",keyValues:"ㄟ"},{id:"80",displayChars:"ㄣ",keyValues:"ㄣ"},{id:"219",displayChars:"[ {",keyValues:"[{"},{id:"221",displayChars:"] }",keyValues:"]}"},{id:"220",displayChars:"\\ |",keyValues:"\\|"}],
        [{id:"20",displayChars:"Caps",keyValues:"Caps"},{id:"65",displayChars:"ㄇ",keyValues:"ㄇ"},{id:"83",displayChars:"ㄋ",keyValues:"ㄋ"},{id:"68",displayChars:"ㄎ",keyValues:"ㄎ"},{id:"70",displayChars:"ㄑ",keyValues:"ㄑ"},{id:"71",displayChars:"ㄕ",keyValues:"ㄕ"},{id:"72",displayChars:"ㄘ",keyValues:"ㄘ"},{id:"74",displayChars:"ㄨ",keyValues:"ㄨ"},{id:"75",displayChars:"ㄜ",keyValues:"ㄜ"},{id:"76",displayChars:"ㄠ",keyValues:"ㄠ"},{id:"186",displayChars:"ㄤ",keyValues:"ㄤ"},{id:"222",displayChars:"\' \"",keyValues:"\'\""},{id:"13",displayChars:"Enter",keyValues:"Enter"}],
        [{id:"16",displayChars:"Shift",keyValues:"Shift"},{id:"90",displayChars:"ㄈ",keyValues:"ㄈ"},{id:"88",displayChars:"ㄌ",keyValues:"ㄌ"},{id:"67",displayChars:"ㄏ",keyValues:"ㄏ"},{id:"86",displayChars:"ㄒ",keyValues:"ㄒ"},{id:"66",displayChars:"ㄖ",keyValues:"ㄖ"},{id:"78",displayChars:"ㄙ",keyValues:"ㄙ"},{id:"77",displayChars:"ㄩ",keyValues:"ㄩ"},{id:"188",displayChars:"ㄝ",keyValues:"ㄝ"},{id:"190",displayChars:"ㄡ",keyValues:"ㄡ"},{id:"191",displayChars:"ㄥ",keyValues:"ㄥ"},{id:"16",displayChars:"Shift",keyValues:"Shift"}],
        [{id:"17",displayChars:"Ctrl",keyValues:"Ctrl"},{id:"91",displayChars:"Win",keyValues:"Win"},{id:"18",displayChars:"Alt",keyValues:"Alt"},{id:"32",displayChars:"Space",keyValues:" "},{id:"18",displayChars:"Win",keyValues:"Win"},{id:"92",displayChars:"Alt",keyValues:"Alt"},{id:"93",displayChars:"Menu",keyValues:"Menu"},{id:"17",displayChars:"Ctrl",keyValues:"Ctrl"}]
    ];
var newJapaneseKeys = [
        [{id:"192",displayChars:"ろ",keyValues:"ろ"},{id:"49",displayChars:"ぬ",keyValues:"ぬ"},{id:"50",displayChars:"ふ",keyValues:"ふ ぶぷ"},{id:"51",displayChars:"あ　ぁ",keyValues:"あぁ"},{id:"52",displayChars:"う　ぅ",keyValues:"うぅ"},{id:"53",displayChars:"え　ぇ",keyValues:"えぇ"},{id:"54",displayChars:"お　ぉ",keyValues:"おぉ"},{id:"55",displayChars:"や　ゃ",keyValues:"やゃ"},{id:"56",displayChars:"ゆ　ゅ",keyValues:"ゆゅ"},{id:"57",displayChars:"よ　ょ",keyValues:"よょ"},{id:"48",displayChars:"わ　を",keyValues:"わを"},{id:"189",displayChars:"ほ",keyValues:"ほ ぼぽ"},{id:"187",displayChars:"へ",keyValues:"へ べぺ"},{id:"8",displayChars:"Delete",keyValues:""}],
        [{id:"9",displayChars:"Tab",keyValues:"Tab"},{id:"81",displayChars:"た",keyValues:"た だ"},{id:"87",displayChars:"て",keyValues:"て で"},{id:"69",displayChars:"い　ぃ",keyValues:"いぃ"},{id:"82",displayChars:"す",keyValues:"す ず"},{id:"84",displayChars:"か",keyValues:"か が"},{id:"89",displayChars:"ん",keyValues:"ん"},{id:"85",displayChars:"な",keyValues:"な"},{id:"73",displayChars:"に",keyValues:"に"},{id:"79",displayChars:"ら",keyValues:"ら"},{id:"80",displayChars:"せ",keyValues:"せ ぜ"},{id:"219",displayChars:"ﾞ",keyValues:"ﾞ"},{id:"221",displayChars:"ﾟ",keyValues:"ﾟ"},{id:"220",displayChars:"む ー",keyValues:"むー"}],
        [{id:"20",displayChars:"Caps",keyValues:"Caps"},{id:"65",displayChars:"ち",keyValues:"ち ぢ"},{id:"83",displayChars:"と",keyValues:"と ど"},{id:"68",displayChars:"し",keyValues:"し じ"},{id:"70",displayChars:"は",keyValues:"は ばぱ"},{id:"71",displayChars:"き",keyValues:"き ぎ"},{id:"72",displayChars:"く",keyValues:"く ぐ"},{id:"74",displayChars:"ま",keyValues:"ま"},{id:"75",displayChars:"の",keyValues:"の"},{id:"76",displayChars:"り",keyValues:"り"},{id:"186",displayChars:"れ",keyValues:"れ"},{id:"222",displayChars:"け",keyValues:"け げ"},{id:"13",displayChars:"Enter",keyValues:"Enter"}],
        [{id:"16",displayChars:"Shift",keyValues:"Shift"},{id:"90",displayChars:"つ　っ",keyValues:"つっづ"},{id:"88",displayChars:"さ",keyValues:"さ ざ"},{id:"67",displayChars:"そ",keyValues:"そ ぞ"},{id:"86",displayChars:"ひ",keyValues:"ひ びぴ"},{id:"66",displayChars:"こ",keyValues:"こ ご"},{id:"78",displayChars:"み",keyValues:"み"},{id:"77",displayChars:"も",keyValues:"も"},{id:"188",displayChars:"ね 、",keyValues:"ね、"},{id:"190",displayChars:"る 。",keyValues:"る。"},{id:"191",displayChars:"め ～",keyValues:"め～"},{id:"16",displayChars:"Shift",keyValues:"Shift"}],
        [{id:"17",displayChars:"Ctrl",keyValues:"Ctrl"},{id:"91",displayChars:"Win",keyValues:"Win"},{id:"18",displayChars:"Alt",keyValues:"Alt"},{id:"32",displayChars:"Space",keyValues:" "},{id:"18",displayChars:"Win",keyValues:"Win"},{id:"92",displayChars:"Alt",keyValues:"Alt"},{id:"93",displayChars:"Menu",keyValues:"Menu"},{id:"17",displayChars:"Ctrl",keyValues:"Ctrl"}]
    ];
var newDvorakKeys = [
        [{id:"192",displayChars:"` ~",keyValues:"`~"},{id:"49",displayChars:"1 !",keyValues:"1!"},{id:"50",displayChars:"2 @",keyValues:"2@"},{id:"51",displayChars:"3 #",keyValues:"3#"},{id:"52",displayChars:"4 $",keyValues:"4 $"},{id:"53",displayChars:"5 %",keyValues:"5 %"},{id:"54",displayChars:"6 ^",keyValues:"6^"},{id:"55",displayChars:"7 &",keyValues:"7&"},{id:"56",displayChars:"8 *",keyValues:"8*"},{id:"57",displayChars:"9 (",keyValues:"9("},{id:"48",displayChars:"0 )",keyValues:"0)"},{id:"189",displayChars:"[ {",keyValues:"[{"},{id:"187",displayChars:"] }",keyValues:"]}"},{id:"8",displayChars:"Backspace",keyValues:""}],
        [{id:"9",displayChars:"Tab",keyValues:"Tab"},{id:"81",displayChars:"\' \"",keyValues:"\'\""},{id:"87",displayChars:", <",keyValues:",<"},{id:"69",displayChars:". >",keyValues:".>"},{id:"82",displayChars:"P",keyValues:"pP"},{id:"84",displayChars:"Y",keyValues:"yY"},{id:"89",displayChars:"F",keyValues:"fF"},{id:"85",displayChars:"G",keyValues:"gG"},{id:"73",displayChars:"C",keyValues:"cC"},{id:"79",displayChars:"R",keyValues:"rR"},{id:"80",displayChars:"L",keyValues:"lL"},{id:"219",displayChars:"/ ?",keyValues:"/?"},{id:"221",displayChars:"= +",keyValues:"=+"},{id:"220",displayChars:"\\ |",keyValues:"\\|"}],
        [{id:"20",displayChars:"Caps",keyValues:"Caps"},{id:"65",displayChars:"A",keyValues:"aA"},{id:"83",displayChars:"O",keyValues:"oO"},{id:"68",displayChars:"E",keyValues:"eE"},{id:"70",displayChars:"U",keyValues:"uU"},{id:"71",displayChars:"I",keyValues:"iI"},{id:"72",displayChars:"D",keyValues:"dD"},{id:"74",displayChars:"H",keyValues:"hH"},{id:"75",displayChars:"T",keyValues:"tT"},{id:"76",displayChars:"N",keyValues:"nN"},{id:"186",displayChars:"S",keyValues:"sS"},{id:"222",displayChars:"- _",keyValues:"-_"},{id:"13",displayChars:"Enter",keyValues:"Enter"}],
        [{id:"16",displayChars:"Shift",keyValues:"Shift"},{id:"90",displayChars:"; :",keyValues:";:"},{id:"88",displayChars:"Q",keyValues:"qQ"},{id:"67",displayChars:"J",keyValues:"jJ"},{id:"86",displayChars:"K",keyValues:"kK"},{id:"66",displayChars:"X",keyValues:"xX"},{id:"78",displayChars:"B",keyValues:"bB"},{id:"77",displayChars:"M",keyValues:"mM"},{id:"188",displayChars:"W",keyValues:"wW"},{id:"190",displayChars:"V",keyValues:"vV"},{id:"191",displayChars:"Z",keyValues:"zZ"},{id:"16",displayChars:"Shift",keyValues:"Shift"}],
        [{id:"17",displayChars:"Ctrl",keyValues:"Ctrl"},{id:"91",displayChars:"Win",keyValues:"Win"},{id:"18",displayChars:"Alt",keyValues:"Alt"},{id:"32",displayChars:"Space",keyValues:" "},{id:"18",displayChars:"Win",keyValues:"Win"},{id:"92",displayChars:"Alt",keyValues:"Alt"},{id:"93",displayChars:"Menu",keyValues:"Menu"},{id:"17",displayChars:"Ctrl",keyValues:"Ctrl"}]
    ];

var taiwaneseWordList = ["ㄓㄨˋ ㄧㄣ ㄈㄨˊ ㄏㄠˋ","ㄅㄨˋ","ㄆㄚˋ","ㄇㄨˇ","ㄈㄨˊ"];
var japaneseWordList = ["はばぱひびぴへべぺふぶぷほぼぽさざしじせぜすずそぞかがきぎけげくぐこごただちぢてでつづとど","これはにほんごのテストです。","おれ、にほんごあんまりわからないよ。","べんきょうがすきじゃないですね。","これはめっちゃむずいな～。"];
var koreanWordList = ["ㅎㅏㄴㄱㅜㄱㅅㅏㄹㅏㅁ","ㅎㅏㄴㄱㅜㄱㅇㅓ","ㅎㅏㄴㄱㅜㄱㅇㅣㄴ","ㄷㅗㅅㅣ","ㅇㅣㄹㅡㅁ","ㅈㅓ","ㄴㅏ","ㄴㅏㅁㅈㅏ"];
var qwertyWordList = [
        "Don’t cry because it’s over, smile because it happened.",
        "Success usually comes to those who are too busy to be looking for it.",
        "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
        "The only way of finding the limits of the possible is by going beyond them into the impossible.",
        "It is hard to fail but it is worse never to have tried to succeed."
    ];
var infoText = [
	"this is a javascript based tool for learning to type with different keyboard layouts.",
	"choose a language / keyboard layout from the dropdown and hit the start button.",
	"the active letter of the example text is highlit and will not progress until the correct keystroke is made.",
	"keyboards are only an aproximation of the true IME and are not usable for anything other than practice typeing."
	];